### ISSUE TITLE
help avoiding conflicts with querypath/querypath

### ISSUE THREAD

**Issue by oppure** [GravityPDF/querypath#52]
**Describe the Feature Request**

hello, it seems that some libraries are still using querypath/querypath and it may happen that in some projects both querypath/querypath and gravitypdf/querypath are installed and this cause a php fatal error (see: https://www.drupal.org/project/feeds_ex/issues/3299193)
**Describe Preferred Solution**

Can adding namespce to qp_functions.php help avoid these conflicts?
Thanks

**If the feature request is approved, would you be willing to submit a PR?**
_(Help can be provided if you need assistance submitting a PR)_

Yes but this would be my first issue.

**Comment by jakejackson1** [comment]
Hey @oppure

Thanks for opening an issue about the dependency conflict.

As this is a fork of the original querypath library and is meant to be a drop-in replacement, I'm hesitant to namespace those global functions and diverge from the original API footprint. 

At a minimum the library should be updated to only define the global functions if they don't already exist: `if ( ! function_exists( 'qp' ) ) { ... }`. That'll prevent the fatal error occurring when another package defines those functions. 

I'm not sure there is anything we can do about others including the older querypath packages. [We already tell Composer this library replaces the original and the first fork](https://github.com/GravityPDF/querypath/blob/main/composer.json#L55-L56). The maintainers of their respective libraries would need to make the decision about what querypath package they choose to include in this codebase. But I'm certainly open to suggestions.

**Comment by oppure** [comment]
HI, ok thanks for replying, I was not aware of these implications of namespacing. Regards.

**Comment by jakejackson1** [comment]
@oppure the `main` branch now contains the guard IF statements on those global functions. Could you test this with https://www.drupal.org/project/feeds_ex/issues/3299193 and see if that prevents the fatal error? You can use `"gravitypdf/querypath": "main-dev"` in Composer to pull down the new code. 

Once you confirm the fix I will tag the 4.0.1 release and push the update to Packagist 👍

**Comment by oppure** [comment]
@jakejackson1 thank you, sorry but I'm having problems doing this test: I forked feeds_ex module and updated its composer.json with your code, I manged to install the forked version of the module on a local drupal 10 install with composer, the strange thing is that composer doesn't seem to install the dependencies and doesn't give any error.
I was able to install and activate both feeds_ex module (which requires gravitypdf/querypath": "main-dev" ) and AMP module (which requires querypath/querypath), there doesn't seem to be any php error, but in vendor directory I can't see any gravitypdf directory, only 'querypath'. I'll try to troublshoot more but at this stage I don't know waht is happening to be honest.

**Comment by jakejackson1** [comment]
@oppure you could try pass `-vvv` to a `composer install -vvv` to get more detailed information about what composer is doing under the hood.

**Comment by oppure** [comment]
@jakejackson1 
$ ddev composer install -vvv
Running 2.8.1 (2024-10-04 11:31:01) with PHP 8.3.12 on Linux / 5.15.153.1-microsoft-standard-WSL2
Reading ./composer.json (/var/www/html/composer.json)
Loading config file ./composer.json (/var/www/html/composer.json)
Checked CA file /etc/pki/tls/certs/ca-bundle.crt does not exist or it is not a file.
Checked directory /etc/pki/tls/certs/ca-bundle.crt does not exist or it is not a directory.
Checked CA file /etc/ssl/certs/ca-certificates.crt: valid
Executing command (/var/www/html): 'git' 'branch' '-a' '--no-color' '--no-abbrev' '-v'
Executing command (/var/www/html): git describe --exact-match --tags
Executing command (CWD): git --version
Executing command (/var/www/html): git log --pretty="%H" -n1 HEAD --no-show-signature
Executing command (/var/www/html): hg branch
Executing command (/var/www/html): fossil branch list
Executing command (/var/www/html): fossil tag list
Executing command (/var/www/html): svn info --xml
Running cache garbage collection
Failed to initialize global composer: Composer could not find the config file: /home/max/.composer/composer.json

Reading /var/www/html/vendor/composer/installed.json
Loading plugin Composer\Installers\Plugin (from composer/installers)
Loading plugin Drupal\Composer\Plugin\Scaffold\Plugin (from drupal/core-composer-scaffold)
Loading plugin Drupal\Composer\Plugin\ProjectMessage\MessagePlugin (from drupal/core-project-message)
Reading ./composer.lock (/var/www/html/composer.lock)
> command: Drupal\Composer\Plugin\Scaffold\Plugin->onCommand
Installing dependencies from lock file (including require-dev)
Verifying lock file contents can be installed on current platform.
Reading ./composer.lock (/var/www/html/composer.lock)
Built pool.
Generating rules
Resolving dependencies through SAT
Looking at all rules.

Dependency resolution completed in 0.001 seconds
Nothing to install, update or remove
Generating autoload files
47 packages you are using are looking for funding.
Use the `composer fund` command to find out more!
> post-install-cmd: Drupal\Composer\Plugin\Scaffold\Plugin->postCmd
Executing command (/var/www/html/web): git ls-files --error-unmatch '/var/www/html/web//autoload.php'
Executing command (/var/www/html): git rev-parse --show-toplevel
> post-install-cmd: Drupal\Composer\Plugin\ProjectMessage\MessagePlugin->displayPostCreateMessage
  * Homepage: https://www.drupal.org/project/drupal
  * Support:
    * docs: https://www.drupal.org/docs/user_guide/en/index.html
    * chat: https://www.drupal.org/node/314178

**Comment by oppure** [comment]
Even if I change "gravitypdf/querypath": "main-dev" to "gravitypdf/querypath": "^3.0 || ^4.0" in the feeds_ex composer.json and then run composer update nothing changes.
If I remove `"repositories": [
		{
            "type": "package",
            "package": {
                "name": "drupal/feeds_ex",
                "version": "1.0-beta",
                "type": "drupal-module",
                "source": {
                    "url": "https://git.drupalcode.org/issue/feeds_ex-3299193.git",
                    "type": "git",
                    "reference": "e6ce9779b00f6b24b097d5426d191afaec2c06c2"
                 }
            }
         },`
from the root composer and run composer update the actual beta5 version is installed with all dependencies including gracitypdf/querypath, if I put the code back and run composer update again the forked version is installe dagain and all dependencies removed.
I will try to ask on the feeds_ex isuue is anyone can try and then update here.

**Comment by jakejackson1** [comment]
I appreciate the update @oppure. Please let me know once this has been properly tested. 👍

**Comment by jakejackson1** [comment]
@oppure https://github.com/GravityPDF/querypath/pull/53 has been included in v4.0.1

**Comment by oppure** [comment]
@jakejackson1 thank you for this improvement, I've reported this in the drupal feed_ex issue.
